### ISSUE TITLE
Temporarily disabled Sonarcloud on PR

### ISSUE THREAD

**Issue by evict** [sourcegraph/sec-pr-audit-trail#362]
Sonarcloud is stuck on this PR: https://github.com/sourcegraph/sourcegraph/pull/51721. As can be seen from the Sonarcloud UI the check did pass, but it did not report back the correct status: https://sonarcloud.io/summary/new_code?id=sourcegraph_sourcegraph&pullRequest=51721.

Will temporarily disable the check so the pipeline can run and we can merge the issue.

**Comment by andreeleuterio** [comment]
I'll a note to the PR
