### ISSUE TITLE
Manually bypassed branch checks (SonarCloud) on https://github.com/sourcegraph/sourcegraph/pull/54784

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sec-pr-audit-trail#387]
https://github.com/sourcegraph/sourcegraph/pull/54784 was stuck on Sonar Cloud, has it happened a lot over the past few days ([discussion](https://sourcegraph.slack.com/archives/C04MYFW01NV/p1689006629573949)). 

@eseliger mentioned that this change was important to get Claude 2 to customers, so I went ahead and: 

- unchecked the _Do not allow bypassing the above settings_ checkbox 
- merged the PR with admin privileges. 
- checked again the _Do not allow bypassing the above settings_ checkbox. 

And created this exception record.

**Comment by jhchabran** [comment]
cc @andreeleuterio @eseliger

**Comment by eseliger** [comment]
thanks for filing!

**Comment by andreeleuterio** [comment]
Approved, thanks for the tag.
