### ISSUE TITLE
sourcegraph/terraform-aws-executors#86: "Update files for 5.2.0 release"

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sec-pr-audit-trail#407]
https://github.com/sourcegraph/terraform-aws-executors/pull/86 "Update files for 5.2.0 release" **has a test plan** but **was not reviewed**.

@unknwon please comment in this issue with an explanation for this exception and close this issue.

**Comment by unknwon** [comment]
Post reviewed
