### ISSUE TITLE
sourcegraph/cody/pull/2151: Fix isRateLimitError

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sec-pr-audit-trail#419]
@philipp-spiess assigning this to you since I can't assign it to @mkondratek

https://github.com/sourcegraph/cody/pull/2151 **had no test plan**

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@philipp-spiess / @mkondratek please comment in this issue with an explanation for this exception and close this issue.

**Comment by philipp-spiess** [comment]
@burmudar Thanks! The test plan was an oversight but the change was tested in JetBrains and is also very trivial (only adds a comparison for a specific string)
