### ISSUE TITLE
sourcegraph/scip-typescript#296: "chore: Bump dependencies"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#420]
https://github.com/sourcegraph/scip-typescript/pull/296 "chore: Bump dependencies" **has a test plan** but **was not reviewed**.

@varungandhi-src please comment in this issue with an explanation for this exception and close this issue.

**Comment by varungandhi-src** [comment]
This was just bumping dependency versions, it didn't need review.
