### ISSUE TITLE
sourcegraph/scip-typescript#299: "chore: Bump version"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#422]
https://github.com/sourcegraph/scip-typescript/pull/299 "chore: Bump version" **has a test plan** but **was not reviewed**.

@varungandhi-src please comment in this issue with an explanation for this exception and close this issue.

**Comment by varungandhi-src** [comment]
Version bump => review not needed.
