### ISSUE TITLE
sourcegraph/scip-typescript#302: "chore: Bump node in Docker images"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#424]
https://github.com/sourcegraph/scip-typescript/pull/302 "chore: Bump node in Docker images" **has a test plan** but **was not reviewed**.

@varungandhi-src please comment in this issue with an explanation for this exception and close this issue.

**Comment by varungandhi-src** [comment]
The PR did not need a review, it was just a version bump.
