### ISSUE TITLE
sourcegraph/scip-typescript#304: "chore: Bump version in package.json again"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#425]
https://github.com/sourcegraph/scip-typescript/pull/304 "chore: Bump version in package.json again" **has a test plan** but **was not reviewed**.

@varungandhi-src please comment in this issue with an explanation for this exception and close this issue.

**Comment by varungandhi-src** [comment]
Changing the package version number doesn't require review.
