### ISSUE TITLE
sourcegraph/sourcegraph#58915: "ci/bazel: use bazel 7"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#427]
https://github.com/sourcegraph/sourcegraph/pull/58915 "ci/bazel: use bazel 7" **has a test plan** but **was not reviewed**.

@jhchabran please comment in this issue with an explanation for this exception and close this issue.

**Comment by jhchabran** [comment]
Accidental mistake, the GitHub UI was showing "this branch is not up to date", which after 4 attempts (each taking 20m in CI) distracted me from the fact that I did not submit a review for the PR. 

I DID review the changes, they're only a few lines, bumping the version of the build system tool we're using.
