### ISSUE TITLE
sourcegraph/docs#22: "Fix ToC in Code Search Features docs"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#429]
https://github.com/sourcegraph/docs/pull/22 "Fix ToC in Code Search Features docs" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@MaedahBatool please comment in this issue with an explanation for this exception and close this issue.

**Comment by MaedahBatool** [comment]
Docs - no tests required.
