### ISSUE TITLE
sourcegraph/cody#2674: "Fixing Steal Cursor Issue"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#434]
https://github.com/sourcegraph/cody/pull/2674 "Fixing Steal Cursor Issue" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@arafatkatze please comment in this issue with an explanation for this exception and close this issue.

**Comment by arafatkatze** [comment]
Originally the test plan was not present coz I wanted to merge the. change in a haste as it was causing a really bad user experience and I wanted to merge it and get a release out soon.

I went back to the PR and added an edit for the Test plan which includes the way to test the work.
Its really simple just use the debugger to test if the cursor is still being taken away.
