### ISSUE TITLE
sourcegraph/cody#2676: "VS Code: Release 1.1.2"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#435]
https://github.com/sourcegraph/cody/pull/2676 "VS Code: Release 1.1.2" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@arafatkatze please comment in this issue with an explanation for this exception and close this issue.

**Comment by arafatkatze** [comment]
An urgent Fix needed to be deployed to prevent BAD User experience with Chat window stealing the cursor
