### ISSUE TITLE
sourcegraph/cody#2690: "fix CI flakes in AutocompleteMatcher.test.ts"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#436]
https://github.com/sourcegraph/cody/pull/2690 "fix CI flakes in AutocompleteMatcher.test.ts" **has a test plan (or does not require one)** but **was not reviewed**.

@sqs please comment in this issue with an explanation for this exception and close this issue.

**Comment by sqs** [comment]
I posted this in Slack at https://sourcegraph.slack.com/archives/C05AGQYD528/p1704971620678049?thread_ts=1704969591.506399&cid=C05AGQYD528 and it got a positive emoji reaction from a team member. It was blocking other builds and was trivial, so I merged it using my admin privileges without review.
