### ISSUE TITLE
sourcegraph/cody#2717: "added IDEA .iml files and vsix to gitignore"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#437]
https://github.com/sourcegraph/cody/pull/2717 "added IDEA .iml files and vsix to gitignore" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@steveyegge please comment in this issue with an explanation for this exception and close this issue.

**Comment by jhchabran** [comment]
PR is a trivial one that adds a `.gitignore` entry.
