### ISSUE TITLE
sourcegraph/docs#38: "Add missing content in Cloud docs"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#439]
https://github.com/sourcegraph/docs/pull/38 "Add missing content in Cloud docs" **has a test plan (or does not require one)** but **was not reviewed**.

@MaedahBatool please comment in this issue with an explanation for this exception and close this issue.

**Comment by MaedahBatool** [comment]
No test plan is required for docs.
