### ISSUE TITLE
sourcegraph/docs#43: "Update preview URLs details in README"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#441]
https://github.com/sourcegraph/docs/pull/43 "Update preview URLs details in README" **has a test plan (or does not require one)** but **was not reviewed**.

@MaedahBatool please comment in this issue with an explanation for this exception and close this issue.

**Comment by MaedahBatool** [comment]
This is a docs pull request, which I tested by previewing my changes locally. As for the review, being a pull request that either adjusts wording or fixes the docsite but doesn't change the content of the docs at a technical level, no review was required.
