### ISSUE TITLE
sourcegraph/cody#2918: "Adding cody ignore docs"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#450]
https://github.com/sourcegraph/cody/pull/2918 "Adding cody ignore docs" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@arafatkatze please comment in this issue with an explanation for this exception and close this issue.

**Comment by arafatkatze** [comment]
Its a documentation PR and my understanding is that documentation doesn't need testing.
