### ISSUE TITLE
sourcegraph/docs#108: "Fix version links to support subpaths"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#463]
https://github.com/sourcegraph/docs/pull/108 "Fix version links to support subpaths" **has a test plan (or does not require one)** but **was not reviewed**.

@MaedahBatool please comment in this issue with an explanation for this exception and close this issue.

**Comment by MaedahBatool** [comment]
No test plan required for docs.
