### ISSUE TITLE
sourcegraph/deploy-sourcegraph-docker#982: "update lib"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#464]
https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/982 "update lib" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@BolajiOlajide please comment in this issue with an explanation for this exception and close this issue.

**Comment by BolajiOlajide** [comment]
To fix an issue with the legacy release tooling that didn't update specific images like:

* jaeger
* executors
