### ISSUE TITLE
sourcegraph/docs#111: "Fix broken links in Admin docs How-to guides"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#465]
https://github.com/sourcegraph/docs/pull/111 "Fix broken links in Admin docs How-to guides" **has a test plan (or does not require one)** but **was not reviewed**.

@MaedahBatool please comment in this issue with an explanation for this exception and close this issue.

**Comment by MaedahBatool** [comment]
This is a documentation pull-request, which I had tested by previewing my changes locally. As for the review, being a pull-request that either adjust wording or fix the docsite but doesn't change the content of the documentation at a technical level, no review was required.
