### ISSUE TITLE
sourcegraph/scip-kotlin#77: "Auto-add labels for filtering in Linear"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#473]
https://github.com/sourcegraph/scip-kotlin/pull/77 "Auto-add labels for filtering in Linear" **has a test plan (or does not require one)** but **was not reviewed**.

@varungandhi-src please comment in this issue with an explanation for this exception and close this issue.

**Comment by varungandhi-src** [comment]
It was about adding issue labels and not connected to the code.
