### ISSUE TITLE
sourcegraph/deploy-sourcegraph#4327: "Pass tokens for uploading SCIP indexes"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#477]
https://github.com/sourcegraph/deploy-sourcegraph/pull/4327 "Pass tokens for uploading SCIP indexes" **has a test plan (or does not require one)** but **was not reviewed**.

@varungandhi-src please comment in this issue with an explanation for this exception and close this issue.

**Comment by varungandhi-src** [comment]
It was related to SCIP uploads which do not affect production.
