### ISSUE TITLE
sourcegraph/docs#332: "fix links to old github discussions (point to new community.sourcegraph.com)"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#479]
https://github.com/sourcegraph/docs/pull/332 "fix links to old github discussions (point to new community.sourcegraph.com)" **has a test plan (or does not require one)** but **was not reviewed**.

@sqs please comment in this issue with an explanation for this exception and close this issue.

**Comment by sqs** [comment]
This is a minor fix
