### ISSUE TITLE
sourcegraph/cody#4316: "Update changelog"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#480]
https://github.com/sourcegraph/cody/pull/4316 "Update changelog" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@thenamankumar please comment in this issue with an explanation for this exception and close this issue.

**Comment by 0xnmn** [comment]
tested manually
