### ISSUE TITLE
sourcegraph/docs#380: "more docs updates for initial context"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#482]
https://github.com/sourcegraph/docs/pull/380 "more docs updates for initial context" **has a test plan (or does not require one)** but **was not reviewed**.

@sqs please comment in this issue with an explanation for this exception and close this issue.

**Comment by sqs** [comment]
Needed to update the docs for the features we shipped on Friday in Cody
