### ISSUE TITLE
sourcegraph/scip-java#707: "new SymbolInformation fields(rebase on main)"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#485]
https://github.com/sourcegraph/scip-java/pull/707 "new SymbolInformation fields(rebase on main)" **has a test plan (or does not require one)** but **was not reviewed**.

@keynmol please comment in this issue with an explanation for this exception and close this issue.

**Comment by keynmol** [comment]
I was the reviewer of the original community PR, and the PR I created was a rebase (because the original author didn't seem to respond to my comments).

**Comment by burmudar** [comment]
Original PR that was reviewed https://github.com/sourcegraph/scip-java/pull/677
