### ISSUE TITLE
sourcegraph/cody#4667: "Revert \"make \"Cody\" the title in the VS Code Marketplace (#4636)\""

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#486]
https://github.com/sourcegraph/cody/pull/4667 "Revert \"make \"Cody\" the title in the VS Code Marketplace (#4636)\"" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@beyang please comment in this issue with an explanation for this exception and close this issue.

**Comment by beyang** [comment]
I've updated the issue with a description of the test plan.
