### ISSUE TITLE
sourcegraph/p4-fusion#35: "Fix openssl build error"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#491]
https://github.com/sourcegraph/p4-fusion/pull/35 "Fix openssl build error" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@pjlast please comment in this issue with an explanation for this exception and close this issue.

**Comment by pjlast** [comment]
Small change to the build script for p4-fusion
