### ISSUE TITLE
sourcegraph/sourcegraph#63499: "cloud: update feature flag warning severity"

### ISSUE THREAD

**Issue by burmudar** [sourcegraph/sec-pr-audit-trail#509]
https://github.com/sourcegraph/sourcegraph/pull/63499 "cloud: update feature flag warning severity" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@michaellzc please comment in this issue with an explanation for this exception and close this issue.

**Comment by michaellzc** [comment]
forgot to add one. it was cosmetic change only
