### ISSUE TITLE
sourcegraph/sourcegraph-sonarqube#22: "workflows: update pr-auditor workflow"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#514]
https://github.com/sourcegraph/sourcegraph-sonarqube/pull/22 "workflows: update pr-auditor workflow" **has a test plan (or does not require one)** but **was not reviewed**.

@BolajiOlajide please comment in this issue with an explanation for this exception and close this issue.

**Comment by BolajiOlajide** [comment]
This was an oversight.

**Comment by burmudar** [comment]
Deprecated repo
