### ISSUE TITLE
sourcegraph/cody#4891: "VS Code: Release 1.26.3"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#515]
https://github.com/sourcegraph/cody/pull/4891 "VS Code: Release 1.26.3" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@umpox please comment in this issue with an explanation for this exception and close this issue.

**Comment by umpox** [comment]
This PR did have a test plan, it seems the GitHub action had a sporadic failure in this case
