### ISSUE TITLE
sourcegraph/cody#4836: "check:manifest uses committed schema cache"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#519]
https://github.com/sourcegraph/cody/pull/4836 "check:manifest uses committed schema cache" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@keegancsmith please comment in this issue with an explanation for this exception and close this issue.

**Comment by keegancsmith** [comment]
It had a test plan, the auditor just changed and didn't detect it.
