### ISSUE TITLE
sourcegraph/sourcegraph#63840: "gitserver: Add option to allow setting custom context line count"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#520]
https://github.com/sourcegraph/sourcegraph/pull/63840 "gitserver: Add option to allow setting custom context line count" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@eseliger please comment in this issue with an explanation for this exception and close this issue.

**Comment by eseliger** [comment]
False positive, this PR does contain a test plan but the format the PR auditor can detect changed in between the PR creation time and when it was merged.
