### ISSUE TITLE
sourcegraph/scip-kotlin#87: "[scip-kotlin] Use the correct linguist language alias for Kotlin for markdown syntax highlighting"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#525]
https://github.com/sourcegraph/scip-kotlin/pull/87 "[scip-kotlin] Use the correct linguist language alias for Kotlin for markdown syntax highlighting" **has a test plan (or does not require one)** but **was not reviewed**.

@varungandhi-src please comment in this issue with an explanation for this exception and close this issue.

**Comment by varungandhi-src** [comment]
It updated snapshot tests, we just forgot to add a test plan to the PR.

**Comment by burmudar** [comment]
Updating of tests
