### ISSUE TITLE
sourcegraph/terraform-google-executors#144: "Revert \"Update executors to 5.5.*\""

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#540]
https://github.com/sourcegraph/terraform-google-executors/pull/144 "Revert \"Update executors to 5.5.*\"" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@jdpleiness please comment in this issue with an explanation for this exception and close this issue.

**Comment by jdpleiness** [comment]
No test plan was required as this was a reversion to a change to documentation.
