### ISSUE TITLE
sourcegraph/scip-java#743: "Also support Java 21"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#584]
https://github.com/sourcegraph/scip-java/pull/743 "Also support Java 21" **has a test plan (or does not require one)** but **was not reviewed**.

@antonsviridov-src please comment in this issue with an explanation for this exception and close this issue.

**Comment by antonsviridov-src** [comment]
Forgot to hit approve
