### ISSUE TITLE
sourcegraph/terraform-aws-executors#137: "Revert \"Release/prepare 5.8.0\""

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#585]
https://github.com/sourcegraph/terraform-aws-executors/pull/137 "Revert \"Release/prepare 5.8.0\"" **has no test plan** and **was not reviewed**.

Learn more about test plans in our [testing guidelines](https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@DaedalusG please comment in this issue with an explanation for this exception and close this issue.

**Comment by DaedalusG** [comment]
Release procedure, tested in CI where a bug exists. Merged on call with reviewers
