### ISSUE TITLE
sourcegraph/terraform-aws-executors#138: "(internal) release_minor: build v5.8.0"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#586]
https://github.com/sourcegraph/terraform-aws-executors/pull/138 "(internal) release_minor: build v5.8.0" **has a test plan (or does not require one)** but **was not reviewed**.

@DaedalusG please comment in this issue with an explanation for this exception and close this issue.

**Comment by DaedalusG** [comment]
Force merged to enable release. Tested in CI. No review required
