### ISSUE TITLE
sourcegraph/deploy-sourcegraph-docker#1097: "(internal) release_patch: build v5.8.0"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#587]
https://github.com/sourcegraph/deploy-sourcegraph-docker/pull/1097 "(internal) release_patch: build v5.8.0" **has a test plan (or does not require one)** but **was not reviewed**.

@DaedalusG please comment in this issue with an explanation for this exception and close this issue.

**Comment by DaedalusG** [comment]
This was part of the release which is tested in CI. No review required
