### ISSUE TITLE
sourcegraph/terraform-google-executors#158: "chore(release): Update version to 5.8.1 latest"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#588]
https://github.com/sourcegraph/terraform-google-executors/pull/158 "chore(release): Update version to 5.8.1 latest" **has a test plan (or does not require one)** but **was not reviewed**.

@DaedalusG please comment in this issue with an explanation for this exception and close this issue.

**Comment by DaedalusG** [comment]
We had a failing test in the release pipeline here related to bugs in the procedure around the README.md file generation. Release was conducted on call with teammates no review required.
