### ISSUE TITLE
sourcegraph/docs#762: "Hackathon - Installation (Clients)"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#589]
https://github.com/sourcegraph/docs/pull/762 "Hackathon - Installation (Clients)" **has a test plan (or does not require one)** but **was not reviewed**.

@MaedahBatool please comment in this issue with an explanation for this exception and close this issue.

**Comment by MaedahBatool** [comment]
I reviewed the PR and merge it.

**Comment by burmudar** [comment]
Just a hackathon PR.
