### ISSUE TITLE
sourcegraph/cody#6098: "Fix for VSCode Marketplace description getting cut-off"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#595]
https://github.com/sourcegraph/cody/pull/6098 "Fix for VSCode Marketplace description getting cut-off" **has no test plan**.

Learn more about test plans in our [testing guidelines](https://docs-legacy.sourcegraph.com/dev/background-information/testing_principles#test-plans).

@beyang please comment in this issue with an explanation for this exception and close this issue.

**Comment by beyang** [comment]
The change only changes marketing copy, doesn't affect app behavior
