### ISSUE TITLE
sourcegraph/cody#6146: "patch highlight.js to address memory leak"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#597]
https://github.com/sourcegraph/cody/pull/6146 "patch highlight.js to address memory leak" **has a test plan (or does not require one)** but **was not reviewed**.

@beyang please comment in this issue with an explanation for this exception and close this issue.

**Comment by beyang** [comment]
Dependency update, not affecting behavior. Perf testing done and results posted in the comments section: https://github.com/sourcegraph/cody/pull/6146
