### ISSUE TITLE
sourcegraph/docs#820: "Highlight postgres 12 end of life doc in technical-changelog"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#598]
https://github.com/sourcegraph/docs/pull/820 "Highlight postgres 12 end of life doc in technical-changelog" **has a test plan (or does not require one)** but **was not reviewed**.

@DaedalusG please comment in this issue with an explanation for this exception and close this issue.

**Comment by DaedalusG** [comment]
This was a last minute docs update that missed merge during the release, important to get in before customers start using the new deployments
